import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Box, Flex, Theme} from "@radix-ui/themes";
import {ThemeProvider} from "next-themes";
import {ToastProvider} from "@radix-ui/react-toast";
import RootNavbar from "@/app/(frontend)/components/RootNavbar";
import {getSession} from "@/app/api/auth/session";

import "@radix-ui/themes/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Burn Admin",
  // description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getSession();

  // const res = await fetch("http://localhost:3000/api/auth/session", {
  //   headers: {
  //     cookie: "",
  //   },
  //   cache: "no-store",
  // });
  //
  // let userId: string | null = null;
  // if (res.ok) {
  //   const sessionResponse = (await res.json()) as GetSessionResponse;
  //   if (sessionResponse.authenticated) {
  //     userId = sessionResponse.userId
  //   }
  // }

  return (
      <html lang="en" suppressHydrationWarning>
      <body style={{all: "unset"}} className={`${geistSans.variable} ${geistMono.variable}`}>
      <ThemeProvider attribute="class">
        <Theme accentColor="purple" grayColor="auto">
          <Flex direction="column" minHeight="100vh" height="100%" style={{background: "var(--mauve-2)"}}>
            <Box position="sticky">
              <RootNavbar session={session}/>
            </Box>

            <ToastProvider>
              {children}
            </ToastProvider>
          </Flex>
        </Theme>
      </ThemeProvider>
      </body>
      </html>
  );
}
